image:
  repository: 620908046246.dkr.ecr.us-east-2.amazonaws.com/realtime
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: api.tucana.sibel.health
      paths:
        - path: /realtime
          pathType: ImplementationSpecific
  tls:
    - secretName: api-tucana-sibel-health-tls
      hosts:
        - api.tucana.sibel.health

app:
  config:
    ENVIRONMENT: "prod"
    SENTRY_DSN: "https://f77b021213b34351966ffa54622c201a@o4504039729135616.ingest.sentry.io/4504951836704768"
    WEB_BASE_URL: "https://api.tucana.sibel.health/web"
    CORS_ORIGINS: "https://cms.tucana.sibel.health,http://localhost:3000"

