"""
Add beds with groups
"""

import sqlalchemy as sa
from alembic import op

revision = "2557c3168208"
down_revision = "aa33ccea10a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bed_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_unique_bed_group_name", "bed_groups", [sa.text("lower(name)")], unique=True)
    op.create_table(
        "beds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("char_length(name) > 0", name="name_min_len"),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id"),
    )
    op.create_index("ix_unique_bed_name", "beds", [sa.text("lower(name)")], unique=True)
    op.create_table(
        "bed_group_association_table",
        sa.Column("bed_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bed_id"],
            ["beds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["bed_groups.id"],
        ),
        sa.PrimaryKeyConstraint("bed_id", "group_id"),
    )
    op.drop_index("ix_unique_group_name", table_name="patient_groups")
    op.create_index(
        "ix_unique_patient_group_name",
        "patient_groups",
        [sa.text("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unique_patient_group_name", table_name="patient_groups")
    op.create_index(
        "ix_unique_group_name",
        "patient_groups",
        [sa.text("lower(name::text)")],
        unique=False,
    )
    op.drop_table("bed_group_association_table")
    op.drop_index("ix_unique_bed_name", table_name="beds")
    op.drop_table("beds")
    op.drop_index("ix_unique_bed_group_name", table_name="bed_groups")
    op.drop_table("bed_groups")
    # ### end Alembic commands ###
