"""
add delete on cascade when a bed is deleted
"""

from alembic import op

revision = "49568342159e"
down_revision = "81d761e7deda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bed_group_association_table_bed_id_fkey",
        "bed_group_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "bed_group_association_table",
        "beds",
        ["bed_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bed_group_association_table", type_="foreignkey")
    op.create_foreign_key(
        "bed_group_association_table_bed_id_fkey",
        "bed_group_association_table",
        "beds",
        ["bed_id"],
        ["id"],
    )
    # ### end Alembic commands ###
