"""
Make bedgroup delete cascade
"""

from alembic import op

revision = "81d761e7deda"
down_revision = "2557c3168208"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bed_group_association_table_group_id_fkey",
        "bed_group_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "bed_group_association_table",
        "bed_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bed_group_association_table", type_="foreignkey")
    op.create_foreign_key(
        "bed_group_association_table_group_id_fkey",
        "bed_group_association_table",
        "bed_groups",
        ["group_id"],
        ["id"],
    )
    # ### end Alembic commands ###
