"""
drop_tenant_id_field
"""

import sqlalchemy as sa
from alembic import op

revision = "a727c9bd8b23"
down_revision = "2fe6ef23d75f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_column("patients", "tenant_id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column("tenant_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
