"""
Remove deprecated patient relation
"""

import sqlalchemy as sa
from alembic import op

revision = "d8f5684aa3e9"
down_revision = "439068f1cda3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("beds_patient_id_key", "beds", type_="unique")
    op.drop_constraint("beds_patient_id_fkey", "beds", type_="foreignkey")
    op.drop_column("beds", "patient_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beds", sa.Column("patient_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key("beds_patient_id_fkey", "beds", "patients", ["patient_id"], ["id"])
    op.create_unique_constraint("beds_patient_id_key", "beds", ["patient_id"])
    # ### end Alembic commands ###
