---
apiVersion: v1
kind: ConfigMap
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::630003401982:role/tucana-monitoring-prod-worker-role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::630003401982:role/AWSReservedSSO_AdministratorAccess_995339c883f62113
      username: cluster-admin
metadata:
  name: aws-auth
  namespace: kube-system