---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cp-ksql-server
  name: ksqldb-cp-ksql-server
  namespace: tucana
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-ksql-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cp-ksql-server
    spec:
      containers:
      - name: cp-ksql-server
        image: confluentinc/ksqldb-server:0.28.2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cp-ksql-server
        env:
        - name: KSQL_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-user-ksqldb
              key: sasl.jaas.config
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi