# Generated by Django 4.1.10 on 2023-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant_id",
            field=models.CharField(default="sibel", max_length=100, verbose_name="tenant_id"),
        ),
    ]
