# Generated by Django 4.1.10 on 2023-08-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
