stages:
  - trivy_scan

variables:
  TRIVY_CACHE_DIR: "/tmp/trivy-cache"

# Define a job to scan the repo with Trivy
trivy_scan:
  stage: trivy_scan
  image: aquasec/trivy:latest  # Official Trivy Docker image
  script:
    - echo "Scanning the entire repository with Trivy..."
    - trivy fs --exit-code 1 --format table --output trivy-report.txt .
  artifacts:
    paths:
      - trivy-report.txt
    when: always
