[package]
name = "rkc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.32.2"
flume = "0.11.0"
futures = "0.3.30"
tokio = {version = "1.36.0", features=["full"]}
rdkafka = {version = "0.36.2", features = ["ssl"]}
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde_derive = "1.0.197"
uuid = { version = "1.7.0", features = ["v4"] }
chrono = {version = "0.4.35", features=["serde"]}
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
reqwest = { version = "0.11", features = ["json"] }
dotenvy = "0.15.7"
config = "0.14.0"

[dev-dependencies]
temp-env = "0.3.6"
test-case = "*"

[[bin]]
name = "rkc"
path = "main.rs"

[profile.release]
strip = "symbols"
