from enum import Enum


class HeaderEventTypes(str, Enum):
    NEW_METRICS = "NEW_METRICS"
    NEW_WAVEFORM_VITALS = "NEW_WAVEFORM_VITALS"
    NEW_ALERT_OBSERVATION = "NEW_ALERT_OBSERVATION"
    BED_ASSIGNED_TO_GROUP_EVENT = "BED_ASSIGNED_TO_GROUP_EVENT"
    BED_REMOVED_FROM_GROUP_EVENT = "BED_REMOVED_FROM_GROUP_EVENT"
    PATIENT_ASSIGNED_TO_BED_EVENT = "PATIENT_ASSIGNED_TO_BED_EVENT"
    PATIENT_UNASSIGNED_FROM_BED_EVENT = "PATIENT_UNASSIGNED_FROM_BED_EVENT"
    SENSOR_REMOVED_EVENT = "SENSOR_REMOVED_EVENT"
