---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cp-ksql-server
  name: ksqldb-cp-ksql-server
  namespace: tucana
spec:
  ports:
  - name: ksql-server
    port: 8088
  selector:
    app: cp-ksql-server