//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.05.09 at 01:02:24 PM UTC
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://standards.ieee.org/downloads/11073/11073-20702-2016",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sibel.mdib.mdpws;
