{{- $secretName := "mirth-keypass-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  KEYSTORE_STOREPASS: {{ $secretData.KEYSTORE_STOREPASS | default (randAlphaNum 10 | b64enc) }}
  KEYSTORE_KEYPASS: {{ $secretData.KEYSTORE_KEYPASS | default (randAlphaNum 10 | b64enc) }}