apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "deploy.fullname" . }}-clean-cache"
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ include "deploy.fullname" . }}-cache-cleaner"
      labels:
        {{- include "deploy.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-c", "from cache import remove_project_cache; remove_project_cache()"]
          env:
          {{- if .Values.app.extraEnvs -}}
          {{ toYaml .Values.app.extraEnvs | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "deploy.fullname" . }}
