# Generated by Django 4.1.10 on 2024-05-31 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variable",
            new_name="AppSetting",
        ),
        migrations.AlterModelOptions(
            name="appsetting",
            options={
                "ordering": ["key"],
                "verbose_name": "application setting",
                "verbose_name_plural": "application settings",
            },
        ),
    ]
