image:
  repository: 678674662538.dkr.ecr.us-east-2.amazonaws.com/audit-trail
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

app:
  config:
    ENVIRONMENT: "qa"
    SENTRY_DSN: "https://4d08e09bcd1b494bbe064ecabd9c3160@o4504039729135616.ingest.sentry.io/4505052165373952"