kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "deploy.fullname" . }}-leader
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
data:
  {{- with .Values.app.config.all -}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.app.config.leader -}}
  {{ toYaml . | nindent 2 }}
  {{- end }}