{{- if .Values.autoscaling.leader.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "deploy.fullname" . }}-leader
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "deploy.fullname" . }}-leader
  minReplicas: {{ .Values.autoscaling.leader.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.leader.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.leader.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.leader.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.leader.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.leader.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}