---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: router-main
spec:
  podMetadata:
    labels:
      component: vmauth
  userSelector: {}
  userNamespaceSelector: {}
  replicaCount: 2
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  ingress:
    name: vmauth-router-main
    tlsSecretName: vm-mon-tucana-sibel-health-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    class_name: nginx
    tlsHosts:
      - vm.mon.tucana.sibel.health