apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cron.name | quote }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy | quote }}
  suspend: {{ .Values.cron.suspended }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python", "remove_old_registries.py"]
              env:
              {{- if .Values.app.extraEnvs -}}
              {{ toYaml .Values.app.extraEnvs | nindent 16 }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "deploy.fullname" . }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: {{ .Values.cron.restartPolicy | quote}}
      backoffLimit: {{ .Values.cron.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.cron.activeDeadlineSeconds }}
