image:
  repository: 104472814609.dkr.ecr.us-east-2.amazonaws.com/sdc
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

app:
  config:
    all:
      LOG_LEVEL: "INFO"
      ENVIRONMENT: "dev"
      SENTRY_DSN: "https://a05f2d9530eb43c78869b628e59e8165@o4504039729135616.ingest.sentry.io/4505404400467968"
      SENTRY_TRACE_SAMPLE_RATE: "0.1"
      SENTRY_PROFILES_SAMPLE_RATE: "0.1"
      FOLLOWER_MAX_CONNECTED_DEVICES: "64"