---
services:
  haproxy:
    image: haproxy:2.7
    container_name: haproxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 6443:6443
      - 6661:6661
      - 3100:3100
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/usr/local/etc/haproxy/certs
    networks:
      - intranet

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./conf/promtail.yml:/etc/promtail.yml
      - ./conf/loki-password:/tmp/loki-password
    command: -config.file=/etc/promtail.yml
    networks:
      - intranet

networks:
  intranet: