image:
  # dev registry for now
  repository: 104472814609.dkr.ecr.us-east-2.amazonaws.com/rkc
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

app:
  config:
    ENVIRONMENT: "hq"
