image:
  repository: 104472814609.dkr.ecr.us-east-2.amazonaws.com/auth
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

app:
  config:
    ENVIRONMENT: "dev"
    SENTRY_DSN: "https://bf6f874c35d14b32a5f904a109f096c2@o4504039729135616.ingest.sentry.io/4504956494413824"
