image:
  repository: 104472814609.dkr.ecr.us-east-2.amazonaws.com/web
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr

ingress:
  enabled: true
  istio: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: api.dev.tucana.sibel.health
      paths:
        - path: /web
          pathType: ImplementationSpecific
  tls:
    - secretName: api-dev-tucana-sibel-health-tls
      hosts:
        - api.dev.tucana.sibel.health

app:
  config:
    ENVIRONMENT: "dev"
    SENTRY_DSN: "https://6fcd1be2c8c3482d886cff9efc165ace@o4504039729135616.ingest.sentry.io/4504803355787264"
    CORS_ORIGINS: "https://cms.dev.tucana.sibel.health,http://localhost:3000"
    DEFAULT_ADMIN_USERNAME: "admin@sibelhealth.com"
    DEFAULT_TECHNICAL_USER_USERNAME: "tech@sibelhealth.com"