{
 "title": "Alerts / Overview",
 "description": "Display Alerts from Prometheus",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Currently Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname != \"Watchdog\" })"
    }
   ]
  },
  {
   "title": "Currently Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate = \"pending\", alertname != \"Watchdog\" })"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Active Alert Rule Definitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules{rule_group!~\".+recording.+\"})"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname != \"Watchdog\" }) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Table - Firing Alerts ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname != \"Watchdog\" }"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\", alertname != \"Watchdog\" }) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Table - Pending Alerts ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"pending\", alertname != \"Watchdog\" }"
    }
   ]
  }
 ]
}