---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: central-hub
spec:
  backup:
    schedule: "0 1 * * *"  # crontab format
    pvcName: pg-backup-pvc
    volumeMount: /var/lib/backup
  replicas: 1
  image: postgres:14.12
  database:
    size: 5Gi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-creds
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-creds
          key: replicationUserPassword

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
  namespace: central-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi