kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
data:
  {{- with .Values.app.config -}}
  {{ toYaml . | nindent 2 }}
  {{- end }}