name: Trivy Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if Trivy is installed
        id: check_trivy
        run: |
          if ! command -v trivy &> /dev/null; then
            echo "Trivy is not installed, installing now..."
            sudo apt-get update && sudo apt-get install -y wget
            wget https://github.com/aquasecurity/trivy/releases/download/v0.45.0/trivy_0.45.0_Linux-x86_64.deb
            sudo dpkg -i trivy_0.45.0_Linux-x86_64.deb
          else
            echo "Trivy is already installed"
          fi

      - name: Run Trivy scan
        run: |
          echo "Running Trivy scan on the repository..."
          trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed .
