# helm repo add jetstack https://charts.jetstack.io
# helm repo update
# helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace \
#   --version v1.11.0 --set installCRDs=true --set 'extraArgs={--acme-http01-solver-nameservers=8.8.8.8:53\,1.1.1.1:53}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: maxim.young@sibelhealth.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx